server:
  port: 8003
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: TaxiEnqueryService-8083
    prefer-ip-address: true
spring:
  application:
    name: TaxiEnqueryService
